FROM node:20

# Use non-root user
USER node

WORKDIR /home/node

# Copy package files first (better caching)
COPY --chown=node:node ../client/package*.json ./client/

WORKDIR /home/node/client
RUN npm install

# Copy rest of the source
COPY --chown=node:node ../client .
EXPOSE 5173

CMD ["npm", "run", "dev"]
